"""Corrected partial unique indices for EventPermission and updated Role/User models

Revision ID: 085f7b8d03bd
Revises: 9b4c0d84e45e
Create Date: 2025-09-18 12:27:12.554500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085f7b8d03bd'
down_revision = '9b4c0d84e45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_permission', schema=None) as batch_op:
        # PASSO 1: Adicionar a coluna role_id TEMPORARIAMENTE como NULLABLE e com um valor padrão.
        #           Este valor padrão (sa.text('1')) será usado para preencher as linhas existentes.
        #           Altere '1' para o ID de uma role padrão se necessário (ex: ID da role 'User' ou 'Admin').
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True, server_default=sa.text('1')))
        
        # PASSO 2: Alterar a coluna role_id para ser NOT NULL e remover o valor padrão.
        #           Isso garante que novas entradas SEMPRE exijam um role_id.
        batch_op.alter_column('role_id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('1')) # Remove o server_default após tornar NOT NULL

        batch_op.create_index('_event_group_unique_idx', ['event_id', 'group_id'], unique=True, postgresql_where=sa.text('group_id IS NOT NULL'))
        batch_op.create_index('_event_user_unique_idx', ['event_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
        batch_op.create_foreign_key('fk_event_permission_role_id', 'role', ['role_id'], ['id'])
        batch_op.drop_column('can_edit')
        batch_op.drop_column('can_view')

    with op.batch_alter_table('role', schema=None) as batch_op:
        # As novas colunas boolenas devem ter um server_default explícito para evitar NOT NULL constraint failed
        batch_op.add_column(sa.Column('can_view_event', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_edit_event', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_manage_permissions', sa.Boolean(), nullable=False, server_default=sa.text('false')))

        # Para remover o server_default após a migração, você pode adicionar:
        # batch_op.alter_column('can_view_event', existing_type=sa.Boolean(), server_default=None)
        # batch_op.alter_column('can_edit_event', existing_type=sa.Boolean(), server_default=None)
        # batch_op.alter_column('can_manage_permissions', existing_type=sa.Boolean(), server_default=None)
        # No entanto, como False é o valor padrão que você quer, manter o server_default 'false' não é um problema.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_manage_permissions')
        batch_op.drop_column('can_edit_event')
        batch_op.drop_column('can_view_event')

    with op.batch_alter_table('event_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view', sa.BOOLEAN(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('can_edit', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))
        batch_op.drop_constraint('fk_event_permission_role_id', type_='foreignkey')
        batch_op.drop_index('_event_user_unique_idx', postgresql_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index('_event_group_unique_idx', postgresql_where=sa.text('group_id IS NOT NULL'))
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
