"""Add explicit foreign_keys to User.uploaded_attachments

Revision ID: 14b83e8fcf86
Revises: 7c93ce72c269
Create Date: 2025-10-09 15:14:06.004526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b83e8fcf86'
down_revision = '7c93ce72c269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('art_approval_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('art_approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('art_approval_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('art_feedback', sa.Text(), nullable=True))
        batch_op.alter_column('filesize',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_attachment_art_approved_by_id', 'user', ['art_approved_by_id'], ['id'])
        batch_op.create_foreign_key('fk_attachment_event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attachment_event_id', type_='foreignkey')
        batch_op.drop_constraint('fk_attachment_art_approved_by_id', type_='foreignkey')
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('filesize',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('art_feedback')
        batch_op.drop_column('art_approval_timestamp')
        batch_op.drop_column('art_approved_by_id')
        batch_op.drop_column('art_approval_status')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
