"""Adiciona campos de conclusao a Task e TaskHistory (tentativa final)

Revision ID: 19454db3b416
Revises: 8a54a5a549b1
Create Date: 2025-09-10 13:24:00.028466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19454db3b416'
down_revision = '8a54a5a549b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta seção foi esvaziada. As operações de adição de colunas
    # e criação da tabela task_history já são realizadas pela migração
    # 72fb9bfe6661, a primeira da sequência a fazer isso.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta seção foi esvaziada. As operações de remoção das colunas
    # e da tabela task_history já são realizadas pela migração
    # 72fb9bfe6661 (ou não são necessárias aqui, visto que esta migração
    # não adicionou nada).
    pass
    # ### end Alembic commands ###