"""Adiciona campos de conclusao a Task e TaskHistory (tentativa final)

Revision ID: 19454db3b416
Revises: 8a54a5a549b1
Create Date: 2025-09-10 13:24:00.028466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19454db3b416'
down_revision = '8a54a5a549b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVIDO: op.drop_table('_alembic_tmp_task') - Esta tabela é temporária e interna do Alembic.

    # ETAPA 1: Adicionar as novas colunas à tabela 'task' como nullable=True (temporariamente)
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True)) # Ajustado para nullable=True
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        # Adiciona a chave estrangeira
        batch_op.create_foreign_key('fk_task_completed_by_id', 'user', ['completed_by_id'], ['id'])

    # ETAPA 2: Atualizar linhas existentes para preencher 'is_completed' com um valor padrão (FALSE)
    # Isso é crucial para tabelas com dados existentes e colunas NOT NULL
    op.execute("UPDATE task SET is_completed = FALSE WHERE is_completed IS NULL")

    # ETAPA 3: Alterar a coluna 'is_completed' para ser NOT NULL
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('is_completed',
                               existing_type=sa.Boolean(),
                               nullable=False,
                               existing_nullable=True, # Informa ao Alembic que era nullable antes
                               server_default=sa.text('FALSE')) # Define o default para novas entradas


    # Criação da tabela 'task_history' (recuperada do seu modelo e do output de migrate anterior)
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_task_history_task_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_task_history_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverte as alterações na tabela 'task'
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_completed_by_id', type_='foreignkey')
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_completed')
    
    # REMOVIDO: op.create_table('_alembic_tmp_task', ...) - Esta tabela não deve ser criada em downgrade.
    
    # Reverte a criação da tabela 'task_history'
    op.drop_table('task_history')
    # ### end Alembic commands ###