"""Add granular task permissions to Role model

Revision ID: 231af5d011b8
Revises: 085f7b8d03bd
Create Date: 2025-09-18 17:48:22.767505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231af5d011b8'
down_revision = '085f7b8d03bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        # Adicionado server_default=sa.text('false') para todas as novas colunas booleanas
        batch_op.add_column(sa.Column('can_create_task', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_edit_task', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_delete_task', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_complete_task', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_uncomplete_task', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_upload_task_audio', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_delete_task_audio', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('can_view_task_history', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_view_task_history')
        batch_op.drop_column('can_delete_task_audio')
        batch_op.drop_column('can_upload_task_audio')
        batch_op.drop_column('can_uncomplete_task')
        batch_op.drop_column('can_complete_task')
        batch_op.drop_column('can_delete_task')
        batch_op.drop_column('can_edit_task')
        batch_op.drop_column('can_create_task')

    # ### end Alembic commands ###