"""Increase password_hash length in User model

Revision ID: 346faa199536
Revises: ccb5454e2ddc
Create Date: 2025-09-11 16:03:01.299482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346faa199536'
down_revision = 'ccb5454e2ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
