"""Initial migration with all current models and can_approve_art

Revision ID: 7c93ce72c269
Revises:
Create Date: 2025-10-09 14:31:27.482087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c93ce72c269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        # 1. Adiciona a coluna temporariamente como nullable=True para permitir valores nulos inicialmente
        batch_op.add_column(sa.Column('can_approve_art', sa.Boolean(), nullable=True))

    # 2. Atualiza os valores existentes na tabela 'role' para FALSE onde a nova coluna é NULL.
    #    Isso é feito fora do batch_alter_table para executar um comando SQL direto.
    op.execute('UPDATE role SET can_approve_art = FALSE WHERE can_approve_art IS NULL')

    with op.batch_alter_table('role', schema=None) as batch_op:
        # 3. Altera a coluna para ser nullable=False e define um valor padrão para futuras inserções
        batch_op.alter_column('can_approve_art',
                               existing_type=sa.Boolean(),
                               nullable=False,
                               existing_nullable=True, # Informa que antes permitia nulos
                               server_default=sa.text('FALSE')) # Define FALSE como padrão para novas linhas

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_approve_art')

    # ### end Alembic commands ###