"""Adiciona creator_id ao modelo Task

Revision ID: 7e4682f4796d
Revises: 88595909030e
Create Date: 2025-10-11 10:55:12.628042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4682f4796d'
down_revision = '88595909030e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_creator_id', 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_creator_id', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
