# C:\gerenciador-eventos\migrations\versions\88595909030e_add_custom_label_and_custom_field_type_.py

"""Add custom_label and custom_field_type to TaskChecklistItem and create custom_field_type_enum type

Revision ID: 88595909030e
Revises: e4cc7dfd2a9b
Create Date: 2025-10-10 14:49:51.341071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88595909030e'
down_revision = 'e4cc7dfd2a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ADICIONADO: Criação explícita do tipo ENUM 'custom_field_type_enum' antes de ser usado.
    # Os valores devem corresponder exatamente ao seu FieldType no models.py.
    op.execute('CREATE TYPE custom_field_type_enum AS ENUM '
               '(\'TEXT\', \'TEXTAREA\', \'DATE\', \'TIME\', \'DATETIME\', '
               '\'NUMBER\', \'BOOLEAN\', \'IMAGE\', \'FILE\', \'URL\', '
               '\'REFERENCE_BIBLICA\', \'SELECT\');')

    with op.batch_alter_table('task_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_label', sa.String(length=255), nullable=True))
        # Usando o tipo ENUM recém-criado
        batch_op.add_column(sa.Column('custom_field_type', sa.Enum('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='custom_field_type_enum'), nullable=True))
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('custom_field_type')
        batch_op.drop_column('custom_label')

    # ADICIONADO: Remoção explícita do tipo ENUM 'custom_field_type_enum' após as colunas serem removidas.
    op.execute('DROP TYPE custom_field_type_enum;')

    # ### end Alembic commands ###