"""Adiciona campos de conclusao a Task e cria modelo TaskHistory (final)

Revision ID: 8a54a5a549b1
Revises: 72fb9bfe6661
Create Date: 2025-09-10 13:05:34.552077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54a5a549b1'
down_revision = '72fb9bfe6661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta seção foi esvaziada. As operações de adição de colunas
    # is_completed, completed_at e completed_by_id já são realizadas
    # pela migração anterior (72fb9bfe6661).
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta seção foi esvaziada. As operações de remoção das colunas
    # correspondentes já são realizadas pela migração anterior (72fb9bfe6661)
    # ou não são necessárias aqui, visto que esta migração não adicionou nada.
    pass
    # ### end Alembic commands ###