"""Adiciona campos de conclusao a Task e cria modelo TaskHistory (final)

Revision ID: 8a54a5a549b1
Revises: 72fb9bfe6661
Create Date: 2025-09-10 13:05:34.552077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54a5a549b1'
down_revision = '72fb9bfe6661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_completed_by_id', 'user', ['completed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_completed_by_id', type_='foreignkey')
        batch_op.drop_column('completed_by_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
