"""Corrige cascade para EventPermission

Revision ID: 9b4c0d84e45e
Revises: 7687abb078c5
Create Date: 2025-09-17 22:12:26.630003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4c0d84e45e'
down_revision = '7687abb078c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_event_user_group_uc'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_event_permission_group_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_event_permission_user_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_event_permission_group_id', 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_event_permission_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_permission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_permission_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_event_permission_group_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_event_permission_user_id'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_event_permission_group_id'), 'group', ['group_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('_event_user_group_uc'), ['event_id', 'user_id', 'group_id'])

    # ### end Alembic commands ###
