"""Add can_create_event to Role model

Revision ID: b8de36bc2850
Revises: 231af5d011b8
Create Date: 2025-09-19 09:12:08.832869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text # <-- LINHA ADICIONADA: Importa a função text

# revision identifiers, used by Alembic.
revision = 'b8de36bc2850'
down_revision = '231af5d011b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        # LINHA MODIFICADA: Adicionado server_default=text('false')
        batch_op.add_column(sa.Column('can_create_event', sa.Boolean(), nullable=False, server_default=text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_create_event')

    # ### end Alembic commands ###