"""Add TaskCategory model and replace event category in Task with task category

Revision ID: ccb5454e2ddc
Revises: 19454db3b416
Create Date: 2025-09-10 15:48:35.803255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb5454e2ddc'
down_revision = '19454db3b416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_category_id', sa.Integer(), nullable=True))
        # A linha abaixo foi o problema. Ao remover 'category_id', as FKs são geralmente limpas.
        # batch_op.drop_constraint(None, type_='foreignkey') # <--- LINHA REMOVIDA/COMENTADA
        batch_op.create_foreign_key('fk_task_task_category_id', 'task_category', ['task_category_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_task_task_category_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('task_category_id')

    op.drop_table('task_category')
    # ### end Alembic commands ###