"""Add TaskSubcategory, ChecklistTemplate, ChecklistItemTemplate, TaskChecklist, TaskChecklistItem models and relationships

Revision ID: e4cc7dfd2a9b
Revises: 14b83e8fcf86
Create Date: 2025-10-09 21:20:14.165444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4cc7dfd2a9b'
down_revision = '14b83e8fcf86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ADICIONADO: Remove o tipo ENUM se ele já existir para evitar o erro de objeto duplicado
    op.execute('DROP TYPE IF EXISTS field_type_enum CASCADE;')

    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_item_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_template_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    # CORREÇÃO AQUI (nome da coluna 'field_type' foi adicionado)
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='field_type_enum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('min_images', sa.Integer(), nullable=True),
    sa.Column('max_images', sa.Integer(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_category_id', sa.Integer(), nullable=False),
    sa.Column('requires_art_approval_on_images', sa.Boolean(), nullable=False),
    sa.Column('checklist_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_template_id'], ['checklist_template.id'], ),
    sa.ForeignKeyConstraint(['task_category_id'], ['task_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_subcategory_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['task_subcategory_id'], ['task_subcategory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('task_checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_checklist_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_template_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    # CORREÇÃO AQUI (nome da coluna 'field_type' foi adicionado)
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='field_type_enum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_time', sa.Time(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_attachment_ids', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_template_id'], ['checklist_item_template.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_checklist_id'], ['task_checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_checklist_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'task_checklist_item', ['task_checklist_item_id'], ['id'])

    with op.batch_alter_table('change_log_entry', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('old_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('new_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'task_subcategory', ['task_subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_task_subcategory_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_subcategory_id')

    with op.batch_alter_table('change_log_entry', schema=None) as batch_op:
        batch_op.alter_column('new_data',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='new_data::json')
        batch_op.alter_column('old_data',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='old_data::json')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_constraint('attachment_task_checklist_item_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_checklist_item_id')

    op.drop_table('task_checklist_item')
    op.drop_table('task_checklist')
    op.drop_table('task_subcategory')
    op.drop_table('checklist_item_template')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###