"""Adicionar coluna 'priority' ao modelo Task

Revision ID: f6d2200752e7
Revises: 37c87cb90ba0
Create Date: 2025-10-22 14:09:26.331677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6d2200752e7'
down_revision = '37c87cb90ba0'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import necessário para postgresql.ENUM

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item_template', schema=None) as batch_op:
        batch_op.alter_column('field_type',
               existing_type=postgresql.ENUM('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='custom_field_type_enum'),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        # A alteração foi feita aqui: adicionado server_default='medium'
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium'))

    with op.batch_alter_table('task_checklist_item', schema=None) as batch_op:
        batch_op.alter_column('custom_field_type',
               existing_type=postgresql.ENUM('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='custom_field_type_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_checklist_item', schema=None) as batch_op:
        batch_op.alter_column('custom_field_type',
               existing_type=postgresql.ENUM('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='custom_field_type_enum'),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('checklist_item_template', schema=None) as batch_op:
        batch_op.alter_column('field_type',
               existing_type=postgresql.ENUM('TEXT', 'TEXTAREA', 'DATE', 'TIME', 'DATETIME', 'NUMBER', 'BOOLEAN', 'IMAGE', 'FILE', 'URL', 'REFERENCE_BIBLICA', 'SELECT', name='custom_field_type_enum'),
               nullable=True)

    # ### end Alembic commands ###
